<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container62ossvd\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container62ossvd/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/Container62ossvd.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\Container62ossvd\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \Container62ossvd\EccubeProdProjectContainer([
    'container.build_hash' => '62ossvd',
    'container.build_id' => 'f2b7319f',
    'container.build_time' => 1608555963,
], __DIR__.\DIRECTORY_SEPARATOR.'Container62ossvd');
